version: "3.9"
name: "kosix"
services:
  postgres:
    container_name: kosix-postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: kosix_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@kosix123
    ports:
      - "6061:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    container_name: kosix-adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "6062:8080"
    depends_on:
      - postgres
